Repository JoshSevy/rancid_tomatillos, pull requests merged in 2020-08, with the labels that each got.

#10 Bm/api class
  src/Api.js
  src/App.js
Labels: React, enhancement

#11 Build Card component and apply it in App
  src/App.js
  src/Card.js
Labels: React, enhancement

#12 Jcs/header
  src/Api.js
  src/App.js
  src/Header.css
  src/Header.js
  src/Login.css
  src/Login.js
  src/index.css
  src/logo.svg
Labels: React, enhancement, styling

#13 Jcs/login
  src/Api/Api.js
  src/App.js
  src/App.test.js
  src/Card/Card.css
  src/Card/Card.js
  src/Card/Card.test.js
  src/CardContainer/CardContainer.css
  src/CardContainer/CardContainer.js
  src/CardContainer/CardContainer.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
Labels: React, Testing

#14 Bm/card styling
  src/App.css
  src/App.js
  src/Card/Card.css
  src/Card/Card.js
Labels: styling

#16 Jcs/card container
  src/App.css
  src/App.js
  src/CardContainer/CardContainer.css
  src/CardContainer/CardContainer.js
Labels: React, enhancement

#15 Bm/login screen shift
  src/App.js
  src/Header/Header.js
  src/Login/Login.css
  src/Login/Login.js
Labels: React, enhancement, styling

#21 Bm/fetch specific movie
  src/App.js
  src/Card/Card.js
  src/CardContainer/CardContainer.js
  src/Movie/Movie.css
  src/Movie/Movie.js
  src/Movie/Movie.test.js
Labels: React, enhancement, styling

#23 Jcs/testing rough
  src/Api/Api.js
  src/App.js
  src/App.test.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/CardContainer/CardContainer.js
  src/CardContainer/CardContainer.test.js
  src/Header/Header.test.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
  src/Movie/Movie.css
  src/Movie/Movie.js
  src/Movie/Movie.test.js
Labels: Testing

#24 Bm/error pages
  src/App.css
  src/App.js
  src/ErrorPage/ErrorPage.css
  src/ErrorPage/ErrorPage.js
  src/ErrorPage/ErrorPage.test.js
  src/Header/Header.js
  src/Login/Login.js
Labels: React, enhancement

#39 Bm/add remove ratings
  src/App.js
  src/Card/Card.js
  src/CardContainer/CardContainer.js
  src/Movie/Movie.js
Labels: React, enhancement

#38 Jcs/refactor testing
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/CardContainer/CardContainer.test.js
  src/ErrorPage/ErrorPage.test.js
  src/Header/Header.test.js
  src/Login/Login.js
  src/Login/Login.test.js
  src/Movie/Movie.test.js
  src/index.js
Labels: React, Testing, enhancement

#43 Jcs/api refactor
  src/Api/Api.js
  src/App/App.js
  src/Card/Card.js
  src/Login/Login.js
  src/Movie/Movie.js
  src/apis/apis.js
Labels: React, enhancement

#44 Add deleteRatingApi functionality and implement
  src/App/App.js
  src/Movie/Movie.js
  src/apis/apis.js
Labels: React, enhancement

#45 Jcs/iteration 6
  README.md
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/CardContainer/CardContainer.js
  src/CardContainer/CardContainer.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
  src/Movie/Movie.test.js
  src/helpers/apis.js
Labels: React, Testing, bugfix, enhancement
